# 无损下线
server:
  shutdown: graceful
spring:
  application:
    name: barley-training-biz
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      add-mappings: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${BARLEY_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/barley_training?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&SSL=true}
    username: ${BARLEY_DATASOURCE_USERNAME:root}
    password: ${BARLEY_DATASOURCE_PASSWORD:wgg234430}
  data:
    # Redis 6.X
    redis:
      host: ${BARLEY_REDIS_HOST:127.0.0.1}
      port: ${BARLEY_REDIS_PORT:6379}
#      password: ${BARLEY_REDIS_PASSWORD:r-uf61dmje3oz816jctp:0ElTRu1TFRcBHLyk}
#      database: ${BARLEY_REDIS_DATABASE:2}
      timeout: 6000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          max-wait: 10
          min-idle: 0
        shutdown-timeout: 100ms
  safety:
    ignoring:
      - /admin/auth/**
      - /client/auth/**
      - /s3/**

barley:
  filecenter:
    s3:
      config:
        - id: FILES
          accessKey: ${BARLEY_S3_ACCESS_KEY:muOqkcIr0dzUSot4MU5p}
          secretKey: ${BARLEY_S3_ACCESS_SECRET_KEY:LdZpTrwAkxnEPaBCxquhDysXY94eFt1nT2DMqUQk}
          bucket: ${BARLEY_S3_BUCKET:barley-training}
          region: ${BARLEY_S3_REGION:shanghai}
          endpoint: ${BARLEY_S3_ENDPOINT:http://127.0.0.1:9000}
          external-endpoint: ${BARLEY_S3_EXTERNAL_ENDPOINT:http://127.0.0.1:9000}